name: 버그 리포트
description: 버그 리포트를 작성합니다. 이 버그 리포트는 Jira와 연동됩니다.
title: "[🐛Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: 버그 리포트를 작성해 주셔서 감사합니다!
  
  - type: textarea
    id: what-happened
    attributes:
      label: 무슨 일이 일어났나요?
      description: 기대했던 동작과 어떤 현상이 보이는지 알려주세요.
      value: |
        - 기대했던 동작:
        - 보이는 현상: 
      render: markdown
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: 이 버그를 만나보기 위해 어떻게 해야 할까요? 
      description: "이 버그를 어떻게 만나게 되었는지 단계별로 설명해주세요."
      value: |
        1.
        2.
        3.
        ...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 어떤 버그가 발생했는지 알 수 있게 어떤 결과가 나왔는지 알려주세요!
      description: 관련 로그 출력을 복사해서 붙여넣어주세요. 자동으로 코드 형식으로 처리되므로 백틱을 사용할 필요는 없어요!
      render: shell
